---
title: "Effects of Reducing Visible Light on Sleep Quality"
subtitle: "2024 Spring 241 Final Project"
author: "Cynthia Xu, Emanuel Mejia, Jonathan Luo, Rina Palta"
date: "4/18/2024"
output:
  pdf_document:
    number_sections: yes
    fig_caption: True
header-includes:
   - \usepackage{rotating, graphicx}
---

```{r import libraries}
library(data.table)
library(sandwich)
library(lmtest)
library(ggplot2)
library(knitr)
library(stargazer)
library(kableExtra)
library(dplyr)
library(ggpubr)
```

```{r with unpaired data}
# Short Format Table
data <- fread("../data/cleaned_data.csv")
data[, avg_ss := rowMeans(.SD, na.rm = TRUE), .SDcols = c("day1_ss", "day2_ss", "day3_ss", "day4_ss")]

# Long Format Table
data_long <- fread("../data/cleaned_data_long.csv")
data_long <- na.omit(data_long)

# Base Model
model_base <- lm(avg_ss ~ treat, data = data)
robust_base <- sqrt(diag(vcovHC(model_base, type="HC1")))

# Model adding with participants' Demographic Info
model_prevsleep <- lm(avg_ss ~ treat + sleep_quality + 
                        trouble_sleep + total_sleep, 
                      data = data)
robust_prevsleep <- sqrt(diag(vcovHC(model_prevsleep, type="HC1")))

# Model adding with participants' Demographic Info
model_demog <- lm(
  avg_ss ~ treat + sleep_quality + trouble_sleep + 
    total_sleep + age_group + gender, 
  data = data)
robust_demog <- sqrt(diag(vcovHC(model_demog, type="HC1")))

# Model with participants' Fixed Effects
model_fixed <- lm(
  avg_ss ~ treat + as.factor(participant_id),
  data = data)
robust_complete <- sqrt(diag(vcovHC(model_fixed, type="HC1")))

# Model with participants' individual data points
# data_long$participant_id <- factor(data_long$participant_id)
model_individual <- lm(
  sleep_score ~ treat + as.factor(participant_id), 
  data = data_long)
robust_individual <- sqrt(diag(vcovHC(model_individual, type="HC1")))
```

```{r regression table, include=TRUE, warning=FALSE, render=FALSE, echo=FALSE, error=FALSE, message=FALSE, results='asis'}
stargazer(model_base, 
          model_prevsleep, 
          model_demog,
          model_fixed,
          model_individual,
          type = 'latex',
          title='Sleep Score Regression Results',
          dep.var.labels = c('Mean Sleep Score','Sleep Score'),
          order="Constant",
          covariate.labels = c("(Intercept)",
                               "Sunglasses Treatment",
                               "Sleep Quality",
                               "Trouble Sleeping",
                               "Typical Total Sleep",
                               "Age Group",
                               "Gender (Female)"
                               ),
          se = list(robust_base, 
                    robust_prevsleep, 
                    robust_demog, 
                    robust_complete),
          # column.sep.width = "-10pt",
          # single.row = TRUE,
          omit = c("participant_id"),
          add.lines=list(c('Participant Fixed effects',
                           'No', 'No', 'No', 'Yes', 'Yes')),
          column.labels = c("Base Model", 
                            "Previous Sleep Info",
                            "Demographic Info",
                            "FE by Participant",
                            "Individual Datapoints"),
          notes = "HC robust standard errors in parantheses.",
          float.env = "sidewaystable",
          font.size = "small",
          no.space = TRUE,
          header = FALSE
          )
```

```{r}
data_survey <- select(
  data, c('sleep_quality','trouble_sleep','total_sleep', 
          'phase_sq', 'phase_ts', 'treat', 'age_group', 'gender', 'participant_id')
  )
stargazer(data_survey, type = "text", title="Descriptive statistics", digits=1)
```

```{r include=TRUE, warning=FALSE, render=FALSE, echo=FALSE, error=FALSE, message=FALSE, results='asis'}

data_prevsleep <- data_survey[ , .(
  'Sleep Quality (Likert 1-5)' = mean(sleep_quality),
  'TroubleSleep (Likert 1-5)' = mean(trouble_sleep),
  'Total Sleep (Hours)' = mean(total_sleep)
  ),
  by = participant_id]
data_prevsleep[, participant_id := NULL]

stargazer(
  data_prevsleep, 
  type = "latex", 
  title="Previous Sleep - Descriptive statistics",
  digits=1,
  header = FALSE
  )
```
```{r}
data_demog <- data_survey[ , .(
  age_group = mean(age_group),
  gender = mean(gender)
  ),
  by = participant_id]

data_demog[, Gender := 'Female']
data_demog[gender == 0, Gender := 'Male']
data_demog[, Age := '25-34']
data_demog[age_group == 3, Age := '35-44']
data_demog[age_group == 4, Age := '45-54']
data_demog[age_group == 5, Age := '55-64']
data_demog[age_group == 6, Age := '65+']

# Crosstable Gender-Age
xtab_ag <- xtabs(~ Gender + Age, data=data_demog)
xtab_ag %>%
  kable(format = "latex", booktabs = T, caption = "Age Group - Gender Distribution")
```


```{r load data}
data <- fread("../data/paired_cleaned_data.csv")

#calculate average sleep scores
data[, avg_ss_ctrl := rowMeans(.SD, na.rm = TRUE), .SDcols = c("day1_ss_ctrl", "day2_ss_ctrl", "day3_ss_ctrl", "day4_ss_ctrl")]
data[, avg_ss_treat := rowMeans(.SD, na.rm = TRUE), .SDcols = c("day1_ss_treat", "day2_ss_treat", "day3_ss_treat", "day4_ss_treat")]
```

```{r distribution of data}
# cols_to_plot <- c("avg_ss_ctrl", "avg_ss_treat", "phase_sq_ctrl", 
#                   "phase_sq_treat", "phase_ts_ctrl", "phase_ts_treat", 
#                   "sleep_quality", "trouble_sleep", "total_sleep")
# 
# for (col in cols_to_plot) {
#   hist(data[[col]], main=paste("Histogram of", col), xlab="Values", ylab="Frequency")
# }

```

```{r hist-density plots, out.width="50%", warning=FALSE, echo=FALSE, error=FALSE, fig.show="hold"}

hist_ctrl <-  ggplot() + 
  geom_histogram(
    aes(data[, avg_ss_ctrl]),
    fill = "#0099F8",
    color="white",
    breaks = seq(50,100,5),
    alpha = 0.6) +
  labs(
    title = "Control Phase",
    subtitle = "Average Sleep Score Distribution",
    x = "Average Sleep Score",
    y = "Frequency"
  ) +
  theme_classic() +
  theme(
    plot.title = element_text(color = "#0099F8",
                              size = 18,
                              face = "bold"),
    plot.subtitle = element_text(color="#969696",
                                   size = 14, 
                                   face = "italic"),
    axis.title = element_text(color = "#969696",
                              size = 12,
                              face = "bold"),
    axis.text = element_text(color = "#969696", size = 12),
    axis.line = element_line(color = "#969696"),
    axis.ticks = element_line(color = data[, .(mean(avg_ss_ctrl))][,V1] - 0.8)
  ) + 
  geom_vline(xintercept = data[, .(mean(avg_ss_ctrl))][,V1], 
             linetype = "dashed", color = "#001F82", size = 1) +
  annotate(
    geom='text', x = data[, .(mean(avg_ss_ctrl))][,V1] - 1, 
    y= 8, label=TeX("$\\mu", output='character'), 
    parse=TRUE, color= "#001F82", size = 7) +
  annotate(
    geom='text', x = data[, .(mean(avg_ss_ctrl))][,V1] - 0.8, 
    y= -0.1, label = round(data[, .(mean(avg_ss_ctrl))][,V1],2), 
    parse=TRUE, color= "#001F82", size = 7) +
  xlim(50,100) + 
  ylim(0,8) + 
  scale_x_continuous(breaks = c(50,60,70,data[, .(mean(avg_ss_ctrl))][,V1], 80,90,100), labels = c("50","60","70",round(data[, .(mean(avg_ss_ctrl))][,V1],1), "80","90","100")) +
  theme(axis.text.x = element_text(color = c("#969696", "#969696", "#969696","#001F82", "#969696","#969696","#969696")),
        axis.ticks.x = element_line(color = c("#969696","#969696","#969696","#001F82", "#969696","#969696","#969696")))

hist_treat <-  ggplot() + 
  geom_histogram(
    aes(data[, avg_ss_treat]),
    fill = "#0099F8",
    color="white",
    breaks = seq(50,100,5),
    alpha = 0.6) +
  labs(
    title = "Treatment Phase",
    subtitle = "Average Sleep Score Distribution",
    x = "Average Sleep Score",
    y = "Frequency"
  ) +
  theme_classic() +
  theme(
    plot.title = element_text(color = "#0099F8",
                              size = 18,
                              face = "bold"),
    plot.subtitle = element_text(color="#969696",
                                   size = 14, 
                                   face = "italic"),
    axis.title = element_text(color = "#969696",
                              size = 12,
                              face = "bold"),
    axis.text = element_text(color = "#969696", size = 12),
    axis.line = element_line(color = "#969696"),
    axis.ticks = element_line(color = "#969696")
  ) + 
  geom_vline(xintercept = data[, .(mean(avg_ss_treat))][,V1], 
             linetype = "dashed", color = "#001F82", size = 1) +
  annotate(
    geom='text', x = data[, .(mean(avg_ss_treat))][,V1] - 1, 
    y= 8, label=TeX("$\\mu", output='character'), 
    parse=TRUE, color= "#001F82", size = 7) +
  annotate(
    geom='text', x = data[, .(mean(avg_ss_treat))][,V1] - 0.9, 
    y= -0.01, label = round(data[, .(mean(avg_ss_treat))][,V1],2), 
    parse=TRUE, color= "#001F82", size = 4) +
  xlim(50,100) +
  ylim(0,8) + 
  scale_x_continuous(breaks = c(50,60,70,data[, .(mean(avg_ss_treat))][,V1], 80,90,100), labels = c("50","60","70",round(data[, .(mean(avg_ss_treat))][,V1],1), "80","90","100")) +
  theme(axis.text.x = element_text(color = c("#969696", "#969696", "#969696","#001F82", "#969696","#969696","#969696")),
        axis.ticks.x = element_line(color = c("#969696","#969696","#969696","#001F82", "#969696","#969696","#969696")))

hist_ctrl
hist_treat
```


```{r}
ggscatter(data, x = "avg_ss_ctrl", y = "avg_ss_treat",
          add = "reg.line", conf.int = TRUE,
          palette = "Blues", color = "#0099F8",
          cor.coef = TRUE, cor.method = "pearson",
          xlab = "Sleep Score Control Phase", 
          ylab = "Sleep Score Treatment Phase") +
  theme_classic() +
  labs(
    title = "Sleep Score Correlation",
    subtitle = "Control - Treatment",
  )+
  theme(
    plot.title = element_text(color = "#0099F8",
                              size = 17,
                              face = "bold"),
    plot.subtitle = element_text(size = 13, 
                                 face = "italic",
                                 color="#969696"),
    axis.title = element_text(color = "#969696",
                              size = 10,
                              face = "bold"),
    axis.text = element_text(color = "#969696", size = 10),
    axis.line = element_line(color = "#969696"),
    axis.ticks = element_line(color = "#969696")
  ) + 
  xlim(55,95) +
  ylim(50,95)
```

```{r}
week_treat <- data_long[ , .(
  sleep_score = mean(sleep_score)
  ),
  keyby = c('treat', 'week', 'Assignment')]

week_treat[treat == 0, Phase := "Control"]
week_treat[treat == 1, Phase := "Treatment"]
week_treat[Assignment == 'ctrl-treat', Assignment := "Control-Treat"]
week_treat[Assignment == 'treat-ctrl', Assignment := "Treat-Control"]

ggplot(week_treat) + 
  geom_point(
    aes(x = week, 
        y = sleep_score,
        shape = Phase,
        color = Assignment),
    size = 5
    ) +
  geom_line(aes(x = week, 
        y = sleep_score,
        color = Assignment)) + 
  theme_classic() +
  labs(
    title = "Sleep Score Evolution",
    subtitle = "Per Week Per Group",
    x = "Week",
    y = "Sleep Score"
  )+
  theme(
    plot.title = element_text(color = "#0099F8",
                              size = 18,
                              face = "bold"),
    plot.subtitle = element_text(size = 14, 
                                 face = "italic",
                                 color="#969696"),
    axis.title = element_text(color = "#969696",
                              size = 12,
                              face = "bold"),
    axis.text = element_text(color = "#969696", size = 10),
    axis.line = element_line(color = "#969696"),
    axis.ticks = element_line(color = "#969696"),
    legend.title = element_text(face = "bold")
  ) + scale_color_manual(values=c('tomato1', '#0099F8')) +
  scale_x_continuous(breaks = c(1,2))
```

```{r}
ggplot(data_long,
       aes(y = sleep_score, phase_sq)) +
  ggtitle("Subjective Score vs Device") + 
  xlab("Subjective Sleep Quality") + 
  ylab("Sleep Score") +
  geom_point(
    alpha = 0.4,
    size = 2,
    color = "#969696"
  ) +
  stat_summary(aes(y = sleep_score,group=1),
               fun.y=mean, colour="#0099F8", geom="line",
               group=1, size = 1.5) +
  theme_classic() +
  theme(
    plot.title = element_text(color = "#0099F8",
                              size = 18,
                              face = "bold"),
    plot.subtitle = element_text(size = 14, 
                                 face = "italic",
                                 color="#969696"),
    axis.title = element_text(color = "#969696",
                              size = 12,
                              face = "bold"),
    axis.text = element_text(color = "#969696", size = 10),
    axis.line = element_line(color = "#969696"),
    axis.ticks = element_line(color = "#969696"),
    legend.title = element_text(face = "bold")
  )
```

